### ISSUE TITLE
[New Tip]: Makefile autogenerated help subcommand

### ISSUE THREAD

**Issue by chilladx** [CircleCI-Public/Config.Tips#59]
### What is the name of the config kind?

Make

### Config Tip

```
help: ## Display this help screen
	@grep -h -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'
```

### Give us a short description of the config kind

Auto generated help subcommand based on the comments of other commands

### Body Area

This snippet handles the `make help` command, and uses the comments from other targets to provide the user with a description of the target. You only need to add a comment (prefixed with `##`) for each target, and the snippet will display it nicely.

**Comment by KyleTryon** [comment]
Thanks for the tip @chilladx ! Would you be interested in making a PR? We'd love to get your picture added to the contributors list! Let me know if I can help in any way

**Comment by chilladx** [comment]
Sure thing, there you go: #60
